# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  neo4j:
    build: .
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - '.neo4j/data:/data'